export type Book = {
  id: string;
  name: string;
  year: number;
  read_date: string[] | null;
  status: "leído" | "leyendo" | "por leer";
  rating: "preferido" | "muy bueno" | "bueno" | "más o menos" | "malo";
  format: "físico" | "digital" | "audiolibro";
  reading_times: number;
  purchased_date: number | null;
  fiction: boolean;
  in_library: boolean;
  book_type: "cuentos" | "novela" | "ensayo";
  purchased_from: string | null;
  cover: string | null;
  editorial: string;
  authors: string;
  author_id: string | null;
  tags: string | null;
};
