INSERT INTO countrys (name, name_en, continent_id) VALUES
    ('Afganistán', 'Afghanistan', 3),
    ('Albania', 'Albania', 4),
    ('Alemania', 'Germany', 4),
    ('Andorra', 'Andorra', 4),
    ('Angola', 'Angola', 1),
    ('Antigua y Barbuda', 'Antigua and Barb.', 2),
    ('Arabia Saudita', 'Saudi Arabia', 3),
    ('Argelia', 'Algeria', 1),
    ('Argentina', 'Argentina', 2),
    ('Armenia', 'Armenia', 4),
    ('Australia', 'Australia', 5),
    ('Austria', 'Austria', 4),
    ('Azerbaiyán', 'Azerbaijan', 3);

INSERT INTO countrys (name, name_en, continent_id) VALUES
    ('Bahamas', 'Bahamas', 2),
    ('Bangladés', 'Bangladesh', 3),
    ('Barbados', 'Barbados', 2),
    ('Baréin', 'Bahrain', 3),
    ('Bélgica', 'Belgium', 4),
    ('Belice', 'Belize', 2),
    ('Benín', 'Benin', 1),
    ('Bielorrusia', 'Belarus', 4),
    ('Myanmar', 'Myanmar', 3),
    ('Bolivia', 'Bolivia', 1),
    ('Bosnia y Herzegovina', 'Bosnia and Herz.', 4),
    ('Botsuana', 'Botswana', 1),
    ('Brasil', 'Brazil', 2),
    ('Brunéi', 'Brunei', 1),
    ('Bulgaria', 'Bulgaria', 4),
    ('Burkina Faso', 'Burkina Faso', 1),
    ('Burundi', 'Burundi', 1),
    ('Bután', 'Bhutan', 3);

INSERT INTO countrys (name, name_en, continent_id) VALUES
    ('Cabo Verde', 'Cape Verde', 1),
    ('Camboya', 'Cambodia', 3),
    ('Camerún', 'Cameroon', 1),
    ('Canadá', 'Canada', 2),
    ('Catar', 'Qatar', 3),
    ('Chad', 'Chad', 1),
    ('Chile', 'Chile', 2),
    ('China', 'China', 3),
    ('Chipre', 'Cyprus', 4),
    ('Ciudad del Vaticano', 'Vatican', 4),
    ('Colombia', 'Colombia', 2),
    ('Comoras', 'Comoros', 1),
    ('Corea del Norte', 'North Korea', 3),
    ('Corea del Sur', 'South Korea', 3),
    ('Costa de Marfil', 'Côte d''Ivoire', 1),
    ('Costa Rica', 'Costa Rica', 2),
    ('Croacia', 'Croatia', 4),
    ('Cuba', 'Cuba', 2);

INSERT INTO countrys (name, name_en, continent_id) VALUES
    ('Dinamarca', 'Denmark', 4),
    ('Dominica', 'Dominica', 2),
    ('Ecuador', 'Ecuador', 2),
    ('Egipto', 'Egypt', 3),
    ('El Salvador', 'El Salvador', 2),
    ('Emiratos Árabes Unidos', 'United Arab Emirates', 3),
    ('Eritrea', 'Eritrea', 1),
    ('Eslovaquia', 'Slovakia', 4),
    ('Eslovenia', 'Slovenia', 4),
    ('España', 'Spain', 4),
    ('Estados Unidos', 'United States of America', 2),
    ('Estonia', 'Estonia', 4),
    ('Etiopía', 'Ethiopia', 1),
    ('Filipinas', 'Philippines', 3),
    ('Finlandia', 'Finland', 4),
    ('Fiyi', 'Fiji', 5),
    ('Francia', 'France', 4);

INSERT INTO countrys (name, name_en, continent_id) VALUES
    ('Gabón', 'Gabon', 1),
    ('Gambia', 'Gambia', 1),
    ('Georgia', 'Georgia', 4),
    ('Ghana', 'Ghana', 1),
    ('Granada', 'Grenada', 2),
    ('Grecia', 'Greece', 4),
    ('Guatemala', 'Guatemala', 2),
    ('Guyana', 'Guyana', 2),
    ('Guinea', 'Guinea', 1),
    ('Guinea-Bisáu', 'Guinea-Bissau', 1),
    ('Guinea Ecuatorial', 'Eq. Guinea', 1),
    ('Haití', 'Haiti', 2),
    ('Honduras', 'Honduras', 2),
    ('Hungría', 'Hungary', 4),
    ('India', 'India', 3),
    ('Indonesia', 'Indonesia', 3),
    ('Irak', 'Iraq', 3),
    ('Irán', 'Iran', 3),
    ('Irlanda', 'Ireland', 4),
    ('Islandia', 'Iceland', 4),
    ('Islas Marshall', 'Marshall Is.', 5),
    ('Islas Salomón', 'Solomon Is.', 5),
    ('Israel', 'Israel', 4),
    ('Italia', 'Italy', 4);

INSERT INTO countrys (name, name_en, continent_id) VALUES
    ('Jamaica', 'Jamaica', 2),
    ('Japón', 'Japan', 3),
    ('Jordania', 'Jordan', 3),
    ('Kazajistán', 'Kazakhstan', 3),
    ('Kenia', 'Kenya', 1),
    ('Kirguistán', 'Kyrgyzstan', 3),
    ('Kiribati', 'Kiribati', 3),
    ('Kuwait', 'Kuwait', 3),
    ('Laos', 'Laos', 1),
    ('Lesoto', 'Lesotho', 1),
    ('Letonia', 'Latvia', 4),
    ('Líbano', 'Lebanon', 1),
    ('Liberia', 'Liberia', 1),
    ('Libia', 'Libya', 1),
    ('Liechtenstein', 'Liechtenstein', 4),
    ('Lituania', 'Lithuania', 4),
    ('Luxemburgo', 'Luxembourg', 4),
    ('Macedonia del Norte', 'North Macedonia', 4),
    ('Madagascar', 'Madagascar', 1),
    ('Malasia', 'Malaysia', 3),
    ('Malaui', 'Malawi', 1),
    ('Maldivas', 'Maldives', 3),
    ('Malí', 'Mali', 1),
    ('Malta', 'Malta', 4),
    ('Marruecos', 'Morocco', 1),
    ('Mauricio', 'Mauritius', 1),
    ('Mauritania', 'Mauritania', 1),
    ('México', 'Mexico', 2),
    ('Micronesia', 'Micronesia', 5),
    ('Moldavia', 'Moldova', 4),
    ('Mónaco', 'Monaco', 4),
    ('Mongolia', 'Mongolia', 3),
    ('Montenegro', 'Montenegro', 4),
    ('Mozambique', 'Mozambique', 1);

INSERT INTO countrys (name, name_en, continent_id) VALUES
    ('Namibia', 'Namibia', 1),
    ('Nauru', 'Nauru', 5),
    ('Nepal', 'Nepal', 3),
    ('Nicaragua', 'Nicaragua', 2),
    ('Níger', 'Niger', 1),
    ('Nigeria', 'Nigeria', 1),
    ('Noruega', 'Norway', 4),
    ('Nueva Zelanda', 'New Zealand', 5),
    ('Omán', 'Oman', 3),
    ('Países Bajos', 'Netherlands', 4),
    ('Pakistán', 'Pakistan', 3),
    ('Palaos', 'Palau', 5),
    ('Palestina', 'Ramala', 3),
    ('Panamá', 'Panama', 2),
    ('Papúa Nueva Guinea', 'Papua New Guinea', 5),
    ('Paraguay', 'Paraguay', 2),
    ('Perú', 'Peru', 2),
    ('Polonia', 'Poland', 4),
    ('Portugal', 'Portugal', 4),
    ('Reino Unido', 'United Kingdom', 4),
    ('República Centroafricana', 'Central African Rep.', 1),
    ('República Checa', 'Czechia', 4),
    ('República del Congo', 'Congo', 1),
    ('República Democrática del Congo', 'Dem. Rep. Congo', 1),
    ('República Dominicana', 'Dominican Rep.', 2),
    ('República Sudafricana', 'South Africa', 1),
    ('Ruanda', 'Rwanda', 1),
    ('Rumanía', 'Romania', 4),
    ('Rusia', 'Russia', 4),
    ('Samoa', 'Samoa', 5),
    ('San Cristóbal y Nieves', 'St. Kitts and Nevis', 2),
    ('San Marino', 'San Marino', 4),
    ('San Vicente y las Granadinas', 'St. Vin. and Gren.', 2),
    ('Santa Lucía', 'Saint Lucia', 2),
    ('Santo Tomé y Príncipe', 'São Tomé and Príncipe', 1),
    ('Senegal', 'Senegal', 1),
    ('Serbia', 'Serbia', 4),
    ('Seychelles', 'Seychelles', 1),
    ('Sierra Leona', 'Sierra Leone', 1),
    ('Singapur', 'Singapore', 3),
    ('Siria', 'Syria', 3),
    ('Somalia', 'Somalia', 1),
    ('Sri Lanka', 'Sri Lanka', 3),
    ('Suazilandia', 'eSwatini', 1),
    ('Sudán', 'Sudan', 1),
    ('Sudán del Sur', 'S. Sudan', 1),
    ('Suecia', 'Sweden', 4),
    ('Suiza', 'Switzerland', 4),
    ('Surinam', 'Suriname', 2),
    ('Tailandia', 'Thailand', 3),
    ('Tanzania', 'Tanzania', 1),
    ('Tayikistán', 'Tajikistan', 3),
    ('Timor Oriental', 'Timor-Leste', 3),
    ('Togo', 'Togo', 1),
    ('Tonga', 'Tonga', 5),
    ('Trinidad y Tobago', 'Trinidad and Tobago', 2),
    ('Túnez', 'Tunisia', 1),
    ('Turkmenistán', 'Turkmenistan', 3),
    ('Turquía', 'Turkey', 3),
    ('Tuvalu', 'Tuvalu', 5),
    ('Ucrania', 'Ukraine', 4),
    ('Uganda', 'Uganda', 1),
    ('Uruguay', 'Uruguay', 2),
    ('Uzbekistán', 'Uzbekistan', 3),
    ('Vanuatu', 'Vanuatu', 5),
    ('Venezuela', 'Venezuela', 2),
    ('Vietnam', 'Vietnam', 3),
    ('Yemen', 'Yemen', 3),
    ('Yibuti', 'Djibouti', 1),
    ('Zambia', 'Zambia', 1),
    ('Zimbabue', 'Zimbabwe', 1);
