INSERT INTO countrys (name, continent_id) VALUES
    ('Afganistán', 3),
    ('Albania', 4),
    ('Alemania', 4),
    ('Andorra', 4),
    ('Angola', 1),
    ('Antigua y Barbuda', 2),
    ('Arabia Saudita', 3),
    ('Argelia', 1),
    ('Argentina', 2),
    ('Armenia', 4),
    ('Australia', 5),
    ('Austria', 4),
    ('Azerbaiyán', 3),
);

1	África
2	América
3	Asia
4	Europa
5	Oceanía

INSERT INTO countrys (name, continent_id) VALUES
    ('Bahamas', 2),
    ('Bangladés', 3),
    ('Barbados', 2),
    ('Baréin', 3),
    ('Bélgica', 4),
    ('Belice', 2),
    ('Benín', 1),
    ('Bielorrusia', 4),
    ('Myanmar', 3),
    ('Bolivia', 1),
    ('Bosnia y Herzegovina', 4),
    ('Botsuana', 1),
    ('Brasil', 2),
    ('Brunéi', 1), 
    ('Bulgaria', 4),
    ('Burkina Faso', 1),
    ('Burundi', 1),
    ('Bután', 3);

INSERT INTO countrys (name, continent_id) VALUES
    ('Cavbo Verde', 1),
    ('Camboya', 3),
    ('Camerún', 1),
    ('Canadá', 2),
    ('Catar', 3),
    ('Chad', 1),
    ('Chile', 2),
    ('China', 3),
    ('Chipre', 4), .
    ('Ciudad del Vaticano', 4),
    ('Colombia', 2),
    ('Comoras', 1),
    ('Corea del Norte', 3),
    ('Corea del Sur', 3),
    ('Costa de Marfil', 1),
    ('Costa Rica', 2),
    ('Croacia', 4),
    ('Cuba', 2);

INSERT INTO countrys (name, continent_id) VALUES
    ('Dinamarca', 4),
    ('Dominica', 2),
    ('Ecuador', 2),
    ('Egipto', 3),
    ('El Salvador', 2),
    ('Emiratos Árabes Unidos', 3),
    ('Eritrea', 1),
    ('Eslovaquia', 4),
    ('Eslovenia', 4),
    ('España', 4),
    ('Estados Unidos', 2),
    ('Estonia', 4),
    ('Etiopía', 1),
    ('Filipinas', 3),
    ('Finlandia', 4),
    ('Fiyi', 5),
    ('Francia', 4);

INSERT INTO countrys (name, continent_id) VALUES
    ('Gabón', 1),
    ('Gambia', 1),
    ('Georgia', 4),
    ('Ghana', 1),
    ('Granada', 2),
    ('Grecia', 4),
    ('Guatemala', 2),
    ('Guyana', 2),
    ('Guinea', 1),
    ('Guinea-Bisáu', 1),
    ('Guinea Ecuatorial', 1),
    ('Haití', 2),
    ('Honduras', 2),
    ('Hungría', 4),
    ('India', 3),
    ('Indonesia', 3),
    ('Irak', 3),
    ('Irán', 3),
    ('Irlanda', 4),
    ('Islandia', 4),
    ('Islas Marshall', 5),
    ('Islas Salomón', 5),
    ('Israel', 4),
    ('Italia', 4);

INSERT INTO countrys (name, continent_id) VALUES
    ('Jamaica', 2),
    ('Japón', 3),
    ('Jordania', 3),
    ('Kazajistán', 3),
    ('Kenia', 1),
    ('Kirguistán', 3),
    ('Kiribati', 3),
    ('Kuwait', 3),
    ('Laos', 1),
    ('Lesoto', 1),
    ('Letonia', 4),
    ('Líbano', 1),
    ('Liberia', 1),
    ('Libia', 1),
    ('Liechtenstein', 4),
    ('Lituania', 4),
    ('Luxemburgo', 4),
    ('Macedonia del Norte', 4),
    ('Madagascar', 1),
    ('Malasia', 3),
    ('Malaui', 1),
    ('Maldivas', 3),
    ('Malí', 1),
    ('Malta', 4),
    ('Marruecos', 1),
    ('Mauricio', 1),
    ('Mauritania', 1),
    ('México', 2),
    ('Micronesia', 5),
    ('Moldavia', 4),
    ('Mónaco', 4),
    ('Mongolia', 3),
    ('Montenegro', 4),
    ('Mozambique', 1);